# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, verbose_name='Username')),
                ('start_date', models.DateTimeField(verbose_name='End date')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
                ('ticket', models.PositiveIntegerField(verbose_name='Ticket No.')),
                ('comment', models.TextField(verbose_name='Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Team name')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, verbose_name='Username')),
                ('file_modified', models.DateTimeField(verbose_name='File mtime')),
            ],
            options={
                'ordering': ('username',),
            },
        ),
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('hours', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='workhours',
            unique_together=set([('year', 'month')]),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(to='vtimecore.User'),
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together=set([('username', 'start_date', 'end_date')]),
        ),
        migrations.AlterIndexTogether(
            name='record',
            index_together=set([('start_date', 'username'), ('ticket',)]),
        ),
    ]
