# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 12:08
from __future__ import unicode_literals

from django.db import migrations


HOURS = (
    (2014, (136, 159, 159, 175, 151, 151, 184, 168, 176, 184, 144, 183)),
    (2015, (120, 152, 168, 175, 143, 167, 184, 168, 176, 176, 159, 183)),
    (2016, (120, 159, 168, 168, 152, 168, 168, 184, 176, 168, 167, 176))
)

def forward(apps, schema_editor):
    m = []

    WorkHours = apps.get_model('vtimecore', 'WorkHours')
    db_alias = schema_editor.connection.alias
    for year, months in HOURS:
        assert len(months) == 12

        for idx, hours in enumerate(months):
            m.append(WorkHours(year=year, month=idx + 1, hours=hours))

    WorkHours.objects.bulk_create(m)


class Migration(migrations.Migration):

    dependencies = [
        ('vtimecore', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
